/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c DBusNokiaMCERequestIf -p dbusnokiamcerequestif.h:dbusnokiamcerequestif.cpp com.nokia.mce.request.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUSNOKIAMCEREQUESTIF_H_1338866958
#define DBUSNOKIAMCEREQUESTIF_H_1338866958

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.nokia.mce.request
 */
class DBusNokiaMCERequestIf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.nokia.mce.request"; }

public:
    DBusNokiaMCERequestIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~DBusNokiaMCERequestIf();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> req_vibrator_pattern_activate(const QString &name)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(name);
        return asyncCallWithArgumentList(QLatin1String("req_vibrator_pattern_activate"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace nokia {
    namespace mce {
      typedef ::DBusNokiaMCERequestIf request;
    }
  }
}
#endif
