/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c DBusIf -p dbusif.h:dbusif.cpp org.scorpius.Yappari.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUSIF_H_1368489962
#define DBUSIF_H_1368489962

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.scorpius.Yappari
 */
class DBusIf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.scorpius.Yappari"; }

public:
    DBusIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~DBusIf();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> ShowWindow()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("ShowWindow"), argumentList);
    }

    inline QDBusPendingReply<bool> isRunning()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("isRunning"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace scorpius {
    typedef ::DBusIf Yappari;
  }
}
#endif
