/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DBusIfAdaptor -a dbusifadaptor.h:dbusifadaptor.cpp org.scorpius.Yappari.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusifadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DBusIfAdaptor
 */

DBusIfAdaptor::DBusIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DBusIfAdaptor::~DBusIfAdaptor()
{
    // destructor
}

void DBusIfAdaptor::ShowWindow()
{
    // handle method call org.scorpius.Yappari.ShowWindow
    QMetaObject::invokeMethod(parent(), "ShowWindow");
}

bool DBusIfAdaptor::isRunning()
{
    // handle method call org.scorpius.Yappari.isRunning
    bool text;
    QMetaObject::invokeMethod(parent(), "isRunning", Q_RETURN_ARG(bool, text));
    return text;
}

