/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c DBusNokiaMCESignalIf -p dbusnokiamcesignalif.h:dbusnokiamcesignalif.cpp com.nokia.mce.signal.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUSNOKIAMCESIGNALIF_H_1368489962
#define DBUSNOKIAMCESIGNALIF_H_1368489962

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.nokia.mce.signal
 */
class DBusNokiaMCESignalIf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.nokia.mce.signal"; }

public:
    DBusNokiaMCESignalIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~DBusNokiaMCESignalIf();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void display_status_ind(const QString &display_mode);
    void tklock_mode_ind(const QString &lock_mode);
};

namespace com {
  namespace nokia {
    namespace mce {
      typedef ::DBusNokiaMCESignalIf signal;
    }
  }
}
#endif
